FROM jwilder/nginx-proxy:alpine

# Change the uid of nginx to the same as mampf-container
RUN usermod -u 501 nginx
RUN sed -i 's/^\(\s*\)location \/ {\(\s\)$/\1location @rails {\2/' /app/nginx.tmpl
RUN mkdir /private /public


COPY docker/production/proxy_server_config.txt /etc/nginx/vhost.d/localhost
COPY docker/production/proxy_location_config.txt /etc/nginx/vhost.d/localhost_location
COPY docker/production/mime.types /etc/nginx/mime.types